language: python
sudo: false
python:
 - "2.7"
 - "3.3"
 - "3.4"
env:
 - DJANGO_VERSION=1.4
 - DJANGO_VERSION=1.6
 - DJANGO_VERSION=1.7
 - DJANGO_VERSION=1.8
install:
 - pip install -q "Django>=${DJANGO_VERSION},<${DJANGO_VERSION}.99" -r travis.txt
script: ./run.sh test
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION=1.4
    - python: "3.4"
      env: DJANGO_VERSION=1.4
